[package]
name = "turn-server"
version = "1.0.3"
edition = "2021"
authors = ["Mr.Panda <xivistudios@gmail.com>"]
description = "A pure rust-implemented turn server."
readme = "../README.md"
homepage = "https://github.com/colourful-rtc/turn-rs"
repository = "https://github.com/colourful-rtc/turn-rs"
license = "GPL-2.0-or-later"
keywords = [
    "stun",
    "webrtc",
    "turn",
    "turn-server"
]

categories = [
    "parsing",
    "network-programming"
]

[dependencies]
turn-rs = { path = "../turn", version = "1.1" }
clap = { version = "4", features = ["derive", "env"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11.13", features = ["json"] }
tower-http = { version = "0.3.5", features = ["cors"] }
async-trait = "0.1.52"
serde_json = "1.0.61"
simple_logger = "4"
num_cpus = "1.13.0"
log = "0.4.11"
anyhow = "1.0"
axum = "0.6.1"
toml = "0.5.10"
tower = "0.4"
http = "0.2.8"
mimalloc = "0.1.34"
